-- ========================================
-- 修改现有的 card_games 表结构
-- ========================================

-- 首先备份表（以防万一）
CREATE TABLE IF NOT EXISTS card_games_backup AS SELECT * FROM card_games;

-- 删除旧表
DROP TABLE IF EXISTS card_games;

-- 创建新的正确结构的表
CREATE TABLE card_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    team1 TEXT[] NOT NULL,
    team2 TEXT[] NOT NULL,
    scores JSONB NOT NULL,
    winner TEXT NOT NULL,
    photo_url TEXT,
    visibility TEXT DEFAULT 'private',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE card_games ENABLE ROW LEVEL SECURITY;

-- 删除可能已存在的策略（避免冲突）
DROP POLICY IF EXISTS "允许查看所有打牌记录" ON card_games;
DROP POLICY IF EXISTS "允许添加打牌记录" ON card_games;
DROP POLICY IF EXISTS "允许更新打牌记录" ON card_games;
DROP POLICY IF EXISTS "允许删除打牌记录" ON card_games;

-- 允许所有用户查看所有打牌记录
CREATE POLICY "允许查看所有打牌记录" ON card_games
    FOR SELECT
    USING (true);

-- 允许所有用户添加打牌记录
CREATE POLICY "允许添加打牌记录" ON card_games
    FOR INSERT
    WITH CHECK (true);

-- 允许所有用户更新打牌记录
CREATE POLICY "允许更新打牌记录" ON card_games
    FOR UPDATE
    USING (true);

-- 允许所有用户删除打牌记录
CREATE POLICY "允许删除打牌记录" ON card_games
    FOR DELETE
    USING (true);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_card_games_updated_at ON card_games;

CREATE TRIGGER update_card_games_updated_at
    BEFORE UPDATE ON card_games
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 完成！
SELECT '表结构修改完成！' AS message;
